# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Volumes/Storage/cache/qhetting/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/183.4588.63/CLion.app/Contents/bin/cmake/mac/bin/cmake"

# The command to remove a file.
RM = "/Volumes/Storage/cache/qhetting/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/183.4588.63/CLion.app/Contents/bin/cmake/mac/bin/cmake" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/qhetting/get_next_line

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/qhetting/get_next_line

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Volumes/Storage/cache/qhetting/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/183.4588.63/CLion.app/Contents/bin/cmake/mac/bin/cmake" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"/Volumes/Storage/cache/qhetting/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/183.4588.63/CLion.app/Contents/bin/cmake/mac/bin/cmake" -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/qhetting/get_next_line/CMakeFiles /Users/qhetting/get_next_line/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/qhetting/get_next_line/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named get_next_line

# Build rule for target.
get_next_line: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 get_next_line
.PHONY : get_next_line

# fast build rule for target.
get_next_line/fast:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/build
.PHONY : get_next_line/fast

get_next_line.o: get_next_line.c.o

.PHONY : get_next_line.o

# target to build an object file
get_next_line.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/get_next_line.c.o
.PHONY : get_next_line.c.o

get_next_line.i: get_next_line.c.i

.PHONY : get_next_line.i

# target to preprocess a source file
get_next_line.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/get_next_line.c.i
.PHONY : get_next_line.c.i

get_next_line.s: get_next_line.c.s

.PHONY : get_next_line.s

# target to generate assembly for a file
get_next_line.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/get_next_line.c.s
.PHONY : get_next_line.c.s

sources/ft_atoi.o: sources/ft_atoi.c.o

.PHONY : sources/ft_atoi.o

# target to build an object file
sources/ft_atoi.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_atoi.c.o
.PHONY : sources/ft_atoi.c.o

sources/ft_atoi.i: sources/ft_atoi.c.i

.PHONY : sources/ft_atoi.i

# target to preprocess a source file
sources/ft_atoi.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_atoi.c.i
.PHONY : sources/ft_atoi.c.i

sources/ft_atoi.s: sources/ft_atoi.c.s

.PHONY : sources/ft_atoi.s

# target to generate assembly for a file
sources/ft_atoi.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_atoi.c.s
.PHONY : sources/ft_atoi.c.s

sources/ft_bzero.o: sources/ft_bzero.c.o

.PHONY : sources/ft_bzero.o

# target to build an object file
sources/ft_bzero.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_bzero.c.o
.PHONY : sources/ft_bzero.c.o

sources/ft_bzero.i: sources/ft_bzero.c.i

.PHONY : sources/ft_bzero.i

# target to preprocess a source file
sources/ft_bzero.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_bzero.c.i
.PHONY : sources/ft_bzero.c.i

sources/ft_bzero.s: sources/ft_bzero.c.s

.PHONY : sources/ft_bzero.s

# target to generate assembly for a file
sources/ft_bzero.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_bzero.c.s
.PHONY : sources/ft_bzero.c.s

sources/ft_cpyuntil.o: sources/ft_cpyuntil.c.o

.PHONY : sources/ft_cpyuntil.o

# target to build an object file
sources/ft_cpyuntil.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_cpyuntil.c.o
.PHONY : sources/ft_cpyuntil.c.o

sources/ft_cpyuntil.i: sources/ft_cpyuntil.c.i

.PHONY : sources/ft_cpyuntil.i

# target to preprocess a source file
sources/ft_cpyuntil.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_cpyuntil.c.i
.PHONY : sources/ft_cpyuntil.c.i

sources/ft_cpyuntil.s: sources/ft_cpyuntil.c.s

.PHONY : sources/ft_cpyuntil.s

# target to generate assembly for a file
sources/ft_cpyuntil.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_cpyuntil.c.s
.PHONY : sources/ft_cpyuntil.c.s

sources/ft_is_null_ptr.o: sources/ft_is_null_ptr.c.o

.PHONY : sources/ft_is_null_ptr.o

# target to build an object file
sources/ft_is_null_ptr.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_is_null_ptr.c.o
.PHONY : sources/ft_is_null_ptr.c.o

sources/ft_is_null_ptr.i: sources/ft_is_null_ptr.c.i

.PHONY : sources/ft_is_null_ptr.i

# target to preprocess a source file
sources/ft_is_null_ptr.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_is_null_ptr.c.i
.PHONY : sources/ft_is_null_ptr.c.i

sources/ft_is_null_ptr.s: sources/ft_is_null_ptr.c.s

.PHONY : sources/ft_is_null_ptr.s

# target to generate assembly for a file
sources/ft_is_null_ptr.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_is_null_ptr.c.s
.PHONY : sources/ft_is_null_ptr.c.s

sources/ft_isalnum.o: sources/ft_isalnum.c.o

.PHONY : sources/ft_isalnum.o

# target to build an object file
sources/ft_isalnum.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_isalnum.c.o
.PHONY : sources/ft_isalnum.c.o

sources/ft_isalnum.i: sources/ft_isalnum.c.i

.PHONY : sources/ft_isalnum.i

# target to preprocess a source file
sources/ft_isalnum.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_isalnum.c.i
.PHONY : sources/ft_isalnum.c.i

sources/ft_isalnum.s: sources/ft_isalnum.c.s

.PHONY : sources/ft_isalnum.s

# target to generate assembly for a file
sources/ft_isalnum.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_isalnum.c.s
.PHONY : sources/ft_isalnum.c.s

sources/ft_isalpha.o: sources/ft_isalpha.c.o

.PHONY : sources/ft_isalpha.o

# target to build an object file
sources/ft_isalpha.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_isalpha.c.o
.PHONY : sources/ft_isalpha.c.o

sources/ft_isalpha.i: sources/ft_isalpha.c.i

.PHONY : sources/ft_isalpha.i

# target to preprocess a source file
sources/ft_isalpha.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_isalpha.c.i
.PHONY : sources/ft_isalpha.c.i

sources/ft_isalpha.s: sources/ft_isalpha.c.s

.PHONY : sources/ft_isalpha.s

# target to generate assembly for a file
sources/ft_isalpha.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_isalpha.c.s
.PHONY : sources/ft_isalpha.c.s

sources/ft_isascii.o: sources/ft_isascii.c.o

.PHONY : sources/ft_isascii.o

# target to build an object file
sources/ft_isascii.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_isascii.c.o
.PHONY : sources/ft_isascii.c.o

sources/ft_isascii.i: sources/ft_isascii.c.i

.PHONY : sources/ft_isascii.i

# target to preprocess a source file
sources/ft_isascii.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_isascii.c.i
.PHONY : sources/ft_isascii.c.i

sources/ft_isascii.s: sources/ft_isascii.c.s

.PHONY : sources/ft_isascii.s

# target to generate assembly for a file
sources/ft_isascii.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_isascii.c.s
.PHONY : sources/ft_isascii.c.s

sources/ft_isblank.o: sources/ft_isblank.c.o

.PHONY : sources/ft_isblank.o

# target to build an object file
sources/ft_isblank.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_isblank.c.o
.PHONY : sources/ft_isblank.c.o

sources/ft_isblank.i: sources/ft_isblank.c.i

.PHONY : sources/ft_isblank.i

# target to preprocess a source file
sources/ft_isblank.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_isblank.c.i
.PHONY : sources/ft_isblank.c.i

sources/ft_isblank.s: sources/ft_isblank.c.s

.PHONY : sources/ft_isblank.s

# target to generate assembly for a file
sources/ft_isblank.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_isblank.c.s
.PHONY : sources/ft_isblank.c.s

sources/ft_isdigit.o: sources/ft_isdigit.c.o

.PHONY : sources/ft_isdigit.o

# target to build an object file
sources/ft_isdigit.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_isdigit.c.o
.PHONY : sources/ft_isdigit.c.o

sources/ft_isdigit.i: sources/ft_isdigit.c.i

.PHONY : sources/ft_isdigit.i

# target to preprocess a source file
sources/ft_isdigit.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_isdigit.c.i
.PHONY : sources/ft_isdigit.c.i

sources/ft_isdigit.s: sources/ft_isdigit.c.s

.PHONY : sources/ft_isdigit.s

# target to generate assembly for a file
sources/ft_isdigit.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_isdigit.c.s
.PHONY : sources/ft_isdigit.c.s

sources/ft_isprint.o: sources/ft_isprint.c.o

.PHONY : sources/ft_isprint.o

# target to build an object file
sources/ft_isprint.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_isprint.c.o
.PHONY : sources/ft_isprint.c.o

sources/ft_isprint.i: sources/ft_isprint.c.i

.PHONY : sources/ft_isprint.i

# target to preprocess a source file
sources/ft_isprint.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_isprint.c.i
.PHONY : sources/ft_isprint.c.i

sources/ft_isprint.s: sources/ft_isprint.c.s

.PHONY : sources/ft_isprint.s

# target to generate assembly for a file
sources/ft_isprint.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_isprint.c.s
.PHONY : sources/ft_isprint.c.s

sources/ft_itoa.o: sources/ft_itoa.c.o

.PHONY : sources/ft_itoa.o

# target to build an object file
sources/ft_itoa.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_itoa.c.o
.PHONY : sources/ft_itoa.c.o

sources/ft_itoa.i: sources/ft_itoa.c.i

.PHONY : sources/ft_itoa.i

# target to preprocess a source file
sources/ft_itoa.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_itoa.c.i
.PHONY : sources/ft_itoa.c.i

sources/ft_itoa.s: sources/ft_itoa.c.s

.PHONY : sources/ft_itoa.s

# target to generate assembly for a file
sources/ft_itoa.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_itoa.c.s
.PHONY : sources/ft_itoa.c.s

sources/ft_lstadd.o: sources/ft_lstadd.c.o

.PHONY : sources/ft_lstadd.o

# target to build an object file
sources/ft_lstadd.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_lstadd.c.o
.PHONY : sources/ft_lstadd.c.o

sources/ft_lstadd.i: sources/ft_lstadd.c.i

.PHONY : sources/ft_lstadd.i

# target to preprocess a source file
sources/ft_lstadd.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_lstadd.c.i
.PHONY : sources/ft_lstadd.c.i

sources/ft_lstadd.s: sources/ft_lstadd.c.s

.PHONY : sources/ft_lstadd.s

# target to generate assembly for a file
sources/ft_lstadd.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_lstadd.c.s
.PHONY : sources/ft_lstadd.c.s

sources/ft_lstaddback.o: sources/ft_lstaddback.c.o

.PHONY : sources/ft_lstaddback.o

# target to build an object file
sources/ft_lstaddback.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_lstaddback.c.o
.PHONY : sources/ft_lstaddback.c.o

sources/ft_lstaddback.i: sources/ft_lstaddback.c.i

.PHONY : sources/ft_lstaddback.i

# target to preprocess a source file
sources/ft_lstaddback.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_lstaddback.c.i
.PHONY : sources/ft_lstaddback.c.i

sources/ft_lstaddback.s: sources/ft_lstaddback.c.s

.PHONY : sources/ft_lstaddback.s

# target to generate assembly for a file
sources/ft_lstaddback.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_lstaddback.c.s
.PHONY : sources/ft_lstaddback.c.s

sources/ft_lstdel.o: sources/ft_lstdel.c.o

.PHONY : sources/ft_lstdel.o

# target to build an object file
sources/ft_lstdel.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_lstdel.c.o
.PHONY : sources/ft_lstdel.c.o

sources/ft_lstdel.i: sources/ft_lstdel.c.i

.PHONY : sources/ft_lstdel.i

# target to preprocess a source file
sources/ft_lstdel.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_lstdel.c.i
.PHONY : sources/ft_lstdel.c.i

sources/ft_lstdel.s: sources/ft_lstdel.c.s

.PHONY : sources/ft_lstdel.s

# target to generate assembly for a file
sources/ft_lstdel.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_lstdel.c.s
.PHONY : sources/ft_lstdel.c.s

sources/ft_lstdelone.o: sources/ft_lstdelone.c.o

.PHONY : sources/ft_lstdelone.o

# target to build an object file
sources/ft_lstdelone.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_lstdelone.c.o
.PHONY : sources/ft_lstdelone.c.o

sources/ft_lstdelone.i: sources/ft_lstdelone.c.i

.PHONY : sources/ft_lstdelone.i

# target to preprocess a source file
sources/ft_lstdelone.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_lstdelone.c.i
.PHONY : sources/ft_lstdelone.c.i

sources/ft_lstdelone.s: sources/ft_lstdelone.c.s

.PHONY : sources/ft_lstdelone.s

# target to generate assembly for a file
sources/ft_lstdelone.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_lstdelone.c.s
.PHONY : sources/ft_lstdelone.c.s

sources/ft_lstiter.o: sources/ft_lstiter.c.o

.PHONY : sources/ft_lstiter.o

# target to build an object file
sources/ft_lstiter.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_lstiter.c.o
.PHONY : sources/ft_lstiter.c.o

sources/ft_lstiter.i: sources/ft_lstiter.c.i

.PHONY : sources/ft_lstiter.i

# target to preprocess a source file
sources/ft_lstiter.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_lstiter.c.i
.PHONY : sources/ft_lstiter.c.i

sources/ft_lstiter.s: sources/ft_lstiter.c.s

.PHONY : sources/ft_lstiter.s

# target to generate assembly for a file
sources/ft_lstiter.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_lstiter.c.s
.PHONY : sources/ft_lstiter.c.s

sources/ft_lstmap.o: sources/ft_lstmap.c.o

.PHONY : sources/ft_lstmap.o

# target to build an object file
sources/ft_lstmap.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_lstmap.c.o
.PHONY : sources/ft_lstmap.c.o

sources/ft_lstmap.i: sources/ft_lstmap.c.i

.PHONY : sources/ft_lstmap.i

# target to preprocess a source file
sources/ft_lstmap.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_lstmap.c.i
.PHONY : sources/ft_lstmap.c.i

sources/ft_lstmap.s: sources/ft_lstmap.c.s

.PHONY : sources/ft_lstmap.s

# target to generate assembly for a file
sources/ft_lstmap.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_lstmap.c.s
.PHONY : sources/ft_lstmap.c.s

sources/ft_lstnew.o: sources/ft_lstnew.c.o

.PHONY : sources/ft_lstnew.o

# target to build an object file
sources/ft_lstnew.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_lstnew.c.o
.PHONY : sources/ft_lstnew.c.o

sources/ft_lstnew.i: sources/ft_lstnew.c.i

.PHONY : sources/ft_lstnew.i

# target to preprocess a source file
sources/ft_lstnew.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_lstnew.c.i
.PHONY : sources/ft_lstnew.c.i

sources/ft_lstnew.s: sources/ft_lstnew.c.s

.PHONY : sources/ft_lstnew.s

# target to generate assembly for a file
sources/ft_lstnew.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_lstnew.c.s
.PHONY : sources/ft_lstnew.c.s

sources/ft_memalloc.o: sources/ft_memalloc.c.o

.PHONY : sources/ft_memalloc.o

# target to build an object file
sources/ft_memalloc.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_memalloc.c.o
.PHONY : sources/ft_memalloc.c.o

sources/ft_memalloc.i: sources/ft_memalloc.c.i

.PHONY : sources/ft_memalloc.i

# target to preprocess a source file
sources/ft_memalloc.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_memalloc.c.i
.PHONY : sources/ft_memalloc.c.i

sources/ft_memalloc.s: sources/ft_memalloc.c.s

.PHONY : sources/ft_memalloc.s

# target to generate assembly for a file
sources/ft_memalloc.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_memalloc.c.s
.PHONY : sources/ft_memalloc.c.s

sources/ft_memccpy.o: sources/ft_memccpy.c.o

.PHONY : sources/ft_memccpy.o

# target to build an object file
sources/ft_memccpy.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_memccpy.c.o
.PHONY : sources/ft_memccpy.c.o

sources/ft_memccpy.i: sources/ft_memccpy.c.i

.PHONY : sources/ft_memccpy.i

# target to preprocess a source file
sources/ft_memccpy.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_memccpy.c.i
.PHONY : sources/ft_memccpy.c.i

sources/ft_memccpy.s: sources/ft_memccpy.c.s

.PHONY : sources/ft_memccpy.s

# target to generate assembly for a file
sources/ft_memccpy.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_memccpy.c.s
.PHONY : sources/ft_memccpy.c.s

sources/ft_memchr.o: sources/ft_memchr.c.o

.PHONY : sources/ft_memchr.o

# target to build an object file
sources/ft_memchr.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_memchr.c.o
.PHONY : sources/ft_memchr.c.o

sources/ft_memchr.i: sources/ft_memchr.c.i

.PHONY : sources/ft_memchr.i

# target to preprocess a source file
sources/ft_memchr.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_memchr.c.i
.PHONY : sources/ft_memchr.c.i

sources/ft_memchr.s: sources/ft_memchr.c.s

.PHONY : sources/ft_memchr.s

# target to generate assembly for a file
sources/ft_memchr.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_memchr.c.s
.PHONY : sources/ft_memchr.c.s

sources/ft_memcmp.o: sources/ft_memcmp.c.o

.PHONY : sources/ft_memcmp.o

# target to build an object file
sources/ft_memcmp.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_memcmp.c.o
.PHONY : sources/ft_memcmp.c.o

sources/ft_memcmp.i: sources/ft_memcmp.c.i

.PHONY : sources/ft_memcmp.i

# target to preprocess a source file
sources/ft_memcmp.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_memcmp.c.i
.PHONY : sources/ft_memcmp.c.i

sources/ft_memcmp.s: sources/ft_memcmp.c.s

.PHONY : sources/ft_memcmp.s

# target to generate assembly for a file
sources/ft_memcmp.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_memcmp.c.s
.PHONY : sources/ft_memcmp.c.s

sources/ft_memcpy.o: sources/ft_memcpy.c.o

.PHONY : sources/ft_memcpy.o

# target to build an object file
sources/ft_memcpy.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_memcpy.c.o
.PHONY : sources/ft_memcpy.c.o

sources/ft_memcpy.i: sources/ft_memcpy.c.i

.PHONY : sources/ft_memcpy.i

# target to preprocess a source file
sources/ft_memcpy.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_memcpy.c.i
.PHONY : sources/ft_memcpy.c.i

sources/ft_memcpy.s: sources/ft_memcpy.c.s

.PHONY : sources/ft_memcpy.s

# target to generate assembly for a file
sources/ft_memcpy.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_memcpy.c.s
.PHONY : sources/ft_memcpy.c.s

sources/ft_memdel.o: sources/ft_memdel.c.o

.PHONY : sources/ft_memdel.o

# target to build an object file
sources/ft_memdel.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_memdel.c.o
.PHONY : sources/ft_memdel.c.o

sources/ft_memdel.i: sources/ft_memdel.c.i

.PHONY : sources/ft_memdel.i

# target to preprocess a source file
sources/ft_memdel.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_memdel.c.i
.PHONY : sources/ft_memdel.c.i

sources/ft_memdel.s: sources/ft_memdel.c.s

.PHONY : sources/ft_memdel.s

# target to generate assembly for a file
sources/ft_memdel.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_memdel.c.s
.PHONY : sources/ft_memdel.c.s

sources/ft_memmove.o: sources/ft_memmove.c.o

.PHONY : sources/ft_memmove.o

# target to build an object file
sources/ft_memmove.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_memmove.c.o
.PHONY : sources/ft_memmove.c.o

sources/ft_memmove.i: sources/ft_memmove.c.i

.PHONY : sources/ft_memmove.i

# target to preprocess a source file
sources/ft_memmove.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_memmove.c.i
.PHONY : sources/ft_memmove.c.i

sources/ft_memmove.s: sources/ft_memmove.c.s

.PHONY : sources/ft_memmove.s

# target to generate assembly for a file
sources/ft_memmove.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_memmove.c.s
.PHONY : sources/ft_memmove.c.s

sources/ft_memset.o: sources/ft_memset.c.o

.PHONY : sources/ft_memset.o

# target to build an object file
sources/ft_memset.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_memset.c.o
.PHONY : sources/ft_memset.c.o

sources/ft_memset.i: sources/ft_memset.c.i

.PHONY : sources/ft_memset.i

# target to preprocess a source file
sources/ft_memset.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_memset.c.i
.PHONY : sources/ft_memset.c.i

sources/ft_memset.s: sources/ft_memset.c.s

.PHONY : sources/ft_memset.s

# target to generate assembly for a file
sources/ft_memset.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_memset.c.s
.PHONY : sources/ft_memset.c.s

sources/ft_putchar.o: sources/ft_putchar.c.o

.PHONY : sources/ft_putchar.o

# target to build an object file
sources/ft_putchar.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_putchar.c.o
.PHONY : sources/ft_putchar.c.o

sources/ft_putchar.i: sources/ft_putchar.c.i

.PHONY : sources/ft_putchar.i

# target to preprocess a source file
sources/ft_putchar.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_putchar.c.i
.PHONY : sources/ft_putchar.c.i

sources/ft_putchar.s: sources/ft_putchar.c.s

.PHONY : sources/ft_putchar.s

# target to generate assembly for a file
sources/ft_putchar.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_putchar.c.s
.PHONY : sources/ft_putchar.c.s

sources/ft_putchar_fd.o: sources/ft_putchar_fd.c.o

.PHONY : sources/ft_putchar_fd.o

# target to build an object file
sources/ft_putchar_fd.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_putchar_fd.c.o
.PHONY : sources/ft_putchar_fd.c.o

sources/ft_putchar_fd.i: sources/ft_putchar_fd.c.i

.PHONY : sources/ft_putchar_fd.i

# target to preprocess a source file
sources/ft_putchar_fd.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_putchar_fd.c.i
.PHONY : sources/ft_putchar_fd.c.i

sources/ft_putchar_fd.s: sources/ft_putchar_fd.c.s

.PHONY : sources/ft_putchar_fd.s

# target to generate assembly for a file
sources/ft_putchar_fd.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_putchar_fd.c.s
.PHONY : sources/ft_putchar_fd.c.s

sources/ft_putendl.o: sources/ft_putendl.c.o

.PHONY : sources/ft_putendl.o

# target to build an object file
sources/ft_putendl.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_putendl.c.o
.PHONY : sources/ft_putendl.c.o

sources/ft_putendl.i: sources/ft_putendl.c.i

.PHONY : sources/ft_putendl.i

# target to preprocess a source file
sources/ft_putendl.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_putendl.c.i
.PHONY : sources/ft_putendl.c.i

sources/ft_putendl.s: sources/ft_putendl.c.s

.PHONY : sources/ft_putendl.s

# target to generate assembly for a file
sources/ft_putendl.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_putendl.c.s
.PHONY : sources/ft_putendl.c.s

sources/ft_putendl_fd.o: sources/ft_putendl_fd.c.o

.PHONY : sources/ft_putendl_fd.o

# target to build an object file
sources/ft_putendl_fd.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_putendl_fd.c.o
.PHONY : sources/ft_putendl_fd.c.o

sources/ft_putendl_fd.i: sources/ft_putendl_fd.c.i

.PHONY : sources/ft_putendl_fd.i

# target to preprocess a source file
sources/ft_putendl_fd.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_putendl_fd.c.i
.PHONY : sources/ft_putendl_fd.c.i

sources/ft_putendl_fd.s: sources/ft_putendl_fd.c.s

.PHONY : sources/ft_putendl_fd.s

# target to generate assembly for a file
sources/ft_putendl_fd.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_putendl_fd.c.s
.PHONY : sources/ft_putendl_fd.c.s

sources/ft_putnbr.o: sources/ft_putnbr.c.o

.PHONY : sources/ft_putnbr.o

# target to build an object file
sources/ft_putnbr.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_putnbr.c.o
.PHONY : sources/ft_putnbr.c.o

sources/ft_putnbr.i: sources/ft_putnbr.c.i

.PHONY : sources/ft_putnbr.i

# target to preprocess a source file
sources/ft_putnbr.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_putnbr.c.i
.PHONY : sources/ft_putnbr.c.i

sources/ft_putnbr.s: sources/ft_putnbr.c.s

.PHONY : sources/ft_putnbr.s

# target to generate assembly for a file
sources/ft_putnbr.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_putnbr.c.s
.PHONY : sources/ft_putnbr.c.s

sources/ft_putnbr_fd.o: sources/ft_putnbr_fd.c.o

.PHONY : sources/ft_putnbr_fd.o

# target to build an object file
sources/ft_putnbr_fd.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_putnbr_fd.c.o
.PHONY : sources/ft_putnbr_fd.c.o

sources/ft_putnbr_fd.i: sources/ft_putnbr_fd.c.i

.PHONY : sources/ft_putnbr_fd.i

# target to preprocess a source file
sources/ft_putnbr_fd.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_putnbr_fd.c.i
.PHONY : sources/ft_putnbr_fd.c.i

sources/ft_putnbr_fd.s: sources/ft_putnbr_fd.c.s

.PHONY : sources/ft_putnbr_fd.s

# target to generate assembly for a file
sources/ft_putnbr_fd.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_putnbr_fd.c.s
.PHONY : sources/ft_putnbr_fd.c.s

sources/ft_putstr.o: sources/ft_putstr.c.o

.PHONY : sources/ft_putstr.o

# target to build an object file
sources/ft_putstr.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_putstr.c.o
.PHONY : sources/ft_putstr.c.o

sources/ft_putstr.i: sources/ft_putstr.c.i

.PHONY : sources/ft_putstr.i

# target to preprocess a source file
sources/ft_putstr.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_putstr.c.i
.PHONY : sources/ft_putstr.c.i

sources/ft_putstr.s: sources/ft_putstr.c.s

.PHONY : sources/ft_putstr.s

# target to generate assembly for a file
sources/ft_putstr.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_putstr.c.s
.PHONY : sources/ft_putstr.c.s

sources/ft_putstr_fd.o: sources/ft_putstr_fd.c.o

.PHONY : sources/ft_putstr_fd.o

# target to build an object file
sources/ft_putstr_fd.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_putstr_fd.c.o
.PHONY : sources/ft_putstr_fd.c.o

sources/ft_putstr_fd.i: sources/ft_putstr_fd.c.i

.PHONY : sources/ft_putstr_fd.i

# target to preprocess a source file
sources/ft_putstr_fd.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_putstr_fd.c.i
.PHONY : sources/ft_putstr_fd.c.i

sources/ft_putstr_fd.s: sources/ft_putstr_fd.c.s

.PHONY : sources/ft_putstr_fd.s

# target to generate assembly for a file
sources/ft_putstr_fd.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_putstr_fd.c.s
.PHONY : sources/ft_putstr_fd.c.s

sources/ft_strcat.o: sources/ft_strcat.c.o

.PHONY : sources/ft_strcat.o

# target to build an object file
sources/ft_strcat.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strcat.c.o
.PHONY : sources/ft_strcat.c.o

sources/ft_strcat.i: sources/ft_strcat.c.i

.PHONY : sources/ft_strcat.i

# target to preprocess a source file
sources/ft_strcat.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strcat.c.i
.PHONY : sources/ft_strcat.c.i

sources/ft_strcat.s: sources/ft_strcat.c.s

.PHONY : sources/ft_strcat.s

# target to generate assembly for a file
sources/ft_strcat.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strcat.c.s
.PHONY : sources/ft_strcat.c.s

sources/ft_strchr.o: sources/ft_strchr.c.o

.PHONY : sources/ft_strchr.o

# target to build an object file
sources/ft_strchr.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strchr.c.o
.PHONY : sources/ft_strchr.c.o

sources/ft_strchr.i: sources/ft_strchr.c.i

.PHONY : sources/ft_strchr.i

# target to preprocess a source file
sources/ft_strchr.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strchr.c.i
.PHONY : sources/ft_strchr.c.i

sources/ft_strchr.s: sources/ft_strchr.c.s

.PHONY : sources/ft_strchr.s

# target to generate assembly for a file
sources/ft_strchr.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strchr.c.s
.PHONY : sources/ft_strchr.c.s

sources/ft_strclr.o: sources/ft_strclr.c.o

.PHONY : sources/ft_strclr.o

# target to build an object file
sources/ft_strclr.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strclr.c.o
.PHONY : sources/ft_strclr.c.o

sources/ft_strclr.i: sources/ft_strclr.c.i

.PHONY : sources/ft_strclr.i

# target to preprocess a source file
sources/ft_strclr.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strclr.c.i
.PHONY : sources/ft_strclr.c.i

sources/ft_strclr.s: sources/ft_strclr.c.s

.PHONY : sources/ft_strclr.s

# target to generate assembly for a file
sources/ft_strclr.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strclr.c.s
.PHONY : sources/ft_strclr.c.s

sources/ft_strcmp.o: sources/ft_strcmp.c.o

.PHONY : sources/ft_strcmp.o

# target to build an object file
sources/ft_strcmp.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strcmp.c.o
.PHONY : sources/ft_strcmp.c.o

sources/ft_strcmp.i: sources/ft_strcmp.c.i

.PHONY : sources/ft_strcmp.i

# target to preprocess a source file
sources/ft_strcmp.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strcmp.c.i
.PHONY : sources/ft_strcmp.c.i

sources/ft_strcmp.s: sources/ft_strcmp.c.s

.PHONY : sources/ft_strcmp.s

# target to generate assembly for a file
sources/ft_strcmp.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strcmp.c.s
.PHONY : sources/ft_strcmp.c.s

sources/ft_strcpy.o: sources/ft_strcpy.c.o

.PHONY : sources/ft_strcpy.o

# target to build an object file
sources/ft_strcpy.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strcpy.c.o
.PHONY : sources/ft_strcpy.c.o

sources/ft_strcpy.i: sources/ft_strcpy.c.i

.PHONY : sources/ft_strcpy.i

# target to preprocess a source file
sources/ft_strcpy.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strcpy.c.i
.PHONY : sources/ft_strcpy.c.i

sources/ft_strcpy.s: sources/ft_strcpy.c.s

.PHONY : sources/ft_strcpy.s

# target to generate assembly for a file
sources/ft_strcpy.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strcpy.c.s
.PHONY : sources/ft_strcpy.c.s

sources/ft_strdel.o: sources/ft_strdel.c.o

.PHONY : sources/ft_strdel.o

# target to build an object file
sources/ft_strdel.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strdel.c.o
.PHONY : sources/ft_strdel.c.o

sources/ft_strdel.i: sources/ft_strdel.c.i

.PHONY : sources/ft_strdel.i

# target to preprocess a source file
sources/ft_strdel.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strdel.c.i
.PHONY : sources/ft_strdel.c.i

sources/ft_strdel.s: sources/ft_strdel.c.s

.PHONY : sources/ft_strdel.s

# target to generate assembly for a file
sources/ft_strdel.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strdel.c.s
.PHONY : sources/ft_strdel.c.s

sources/ft_strdup.o: sources/ft_strdup.c.o

.PHONY : sources/ft_strdup.o

# target to build an object file
sources/ft_strdup.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strdup.c.o
.PHONY : sources/ft_strdup.c.o

sources/ft_strdup.i: sources/ft_strdup.c.i

.PHONY : sources/ft_strdup.i

# target to preprocess a source file
sources/ft_strdup.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strdup.c.i
.PHONY : sources/ft_strdup.c.i

sources/ft_strdup.s: sources/ft_strdup.c.s

.PHONY : sources/ft_strdup.s

# target to generate assembly for a file
sources/ft_strdup.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strdup.c.s
.PHONY : sources/ft_strdup.c.s

sources/ft_strequ.o: sources/ft_strequ.c.o

.PHONY : sources/ft_strequ.o

# target to build an object file
sources/ft_strequ.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strequ.c.o
.PHONY : sources/ft_strequ.c.o

sources/ft_strequ.i: sources/ft_strequ.c.i

.PHONY : sources/ft_strequ.i

# target to preprocess a source file
sources/ft_strequ.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strequ.c.i
.PHONY : sources/ft_strequ.c.i

sources/ft_strequ.s: sources/ft_strequ.c.s

.PHONY : sources/ft_strequ.s

# target to generate assembly for a file
sources/ft_strequ.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strequ.c.s
.PHONY : sources/ft_strequ.c.s

sources/ft_striter.o: sources/ft_striter.c.o

.PHONY : sources/ft_striter.o

# target to build an object file
sources/ft_striter.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_striter.c.o
.PHONY : sources/ft_striter.c.o

sources/ft_striter.i: sources/ft_striter.c.i

.PHONY : sources/ft_striter.i

# target to preprocess a source file
sources/ft_striter.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_striter.c.i
.PHONY : sources/ft_striter.c.i

sources/ft_striter.s: sources/ft_striter.c.s

.PHONY : sources/ft_striter.s

# target to generate assembly for a file
sources/ft_striter.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_striter.c.s
.PHONY : sources/ft_striter.c.s

sources/ft_striteri.o: sources/ft_striteri.c.o

.PHONY : sources/ft_striteri.o

# target to build an object file
sources/ft_striteri.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_striteri.c.o
.PHONY : sources/ft_striteri.c.o

sources/ft_striteri.i: sources/ft_striteri.c.i

.PHONY : sources/ft_striteri.i

# target to preprocess a source file
sources/ft_striteri.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_striteri.c.i
.PHONY : sources/ft_striteri.c.i

sources/ft_striteri.s: sources/ft_striteri.c.s

.PHONY : sources/ft_striteri.s

# target to generate assembly for a file
sources/ft_striteri.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_striteri.c.s
.PHONY : sources/ft_striteri.c.s

sources/ft_strjoin.o: sources/ft_strjoin.c.o

.PHONY : sources/ft_strjoin.o

# target to build an object file
sources/ft_strjoin.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strjoin.c.o
.PHONY : sources/ft_strjoin.c.o

sources/ft_strjoin.i: sources/ft_strjoin.c.i

.PHONY : sources/ft_strjoin.i

# target to preprocess a source file
sources/ft_strjoin.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strjoin.c.i
.PHONY : sources/ft_strjoin.c.i

sources/ft_strjoin.s: sources/ft_strjoin.c.s

.PHONY : sources/ft_strjoin.s

# target to generate assembly for a file
sources/ft_strjoin.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strjoin.c.s
.PHONY : sources/ft_strjoin.c.s

sources/ft_strjoinch.o: sources/ft_strjoinch.c.o

.PHONY : sources/ft_strjoinch.o

# target to build an object file
sources/ft_strjoinch.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strjoinch.c.o
.PHONY : sources/ft_strjoinch.c.o

sources/ft_strjoinch.i: sources/ft_strjoinch.c.i

.PHONY : sources/ft_strjoinch.i

# target to preprocess a source file
sources/ft_strjoinch.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strjoinch.c.i
.PHONY : sources/ft_strjoinch.c.i

sources/ft_strjoinch.s: sources/ft_strjoinch.c.s

.PHONY : sources/ft_strjoinch.s

# target to generate assembly for a file
sources/ft_strjoinch.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strjoinch.c.s
.PHONY : sources/ft_strjoinch.c.s

sources/ft_strjoinf.o: sources/ft_strjoinf.c.o

.PHONY : sources/ft_strjoinf.o

# target to build an object file
sources/ft_strjoinf.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strjoinf.c.o
.PHONY : sources/ft_strjoinf.c.o

sources/ft_strjoinf.i: sources/ft_strjoinf.c.i

.PHONY : sources/ft_strjoinf.i

# target to preprocess a source file
sources/ft_strjoinf.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strjoinf.c.i
.PHONY : sources/ft_strjoinf.c.i

sources/ft_strjoinf.s: sources/ft_strjoinf.c.s

.PHONY : sources/ft_strjoinf.s

# target to generate assembly for a file
sources/ft_strjoinf.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strjoinf.c.s
.PHONY : sources/ft_strjoinf.c.s

sources/ft_strlcat.o: sources/ft_strlcat.c.o

.PHONY : sources/ft_strlcat.o

# target to build an object file
sources/ft_strlcat.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strlcat.c.o
.PHONY : sources/ft_strlcat.c.o

sources/ft_strlcat.i: sources/ft_strlcat.c.i

.PHONY : sources/ft_strlcat.i

# target to preprocess a source file
sources/ft_strlcat.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strlcat.c.i
.PHONY : sources/ft_strlcat.c.i

sources/ft_strlcat.s: sources/ft_strlcat.c.s

.PHONY : sources/ft_strlcat.s

# target to generate assembly for a file
sources/ft_strlcat.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strlcat.c.s
.PHONY : sources/ft_strlcat.c.s

sources/ft_strlen.o: sources/ft_strlen.c.o

.PHONY : sources/ft_strlen.o

# target to build an object file
sources/ft_strlen.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strlen.c.o
.PHONY : sources/ft_strlen.c.o

sources/ft_strlen.i: sources/ft_strlen.c.i

.PHONY : sources/ft_strlen.i

# target to preprocess a source file
sources/ft_strlen.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strlen.c.i
.PHONY : sources/ft_strlen.c.i

sources/ft_strlen.s: sources/ft_strlen.c.s

.PHONY : sources/ft_strlen.s

# target to generate assembly for a file
sources/ft_strlen.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strlen.c.s
.PHONY : sources/ft_strlen.c.s

sources/ft_strmap.o: sources/ft_strmap.c.o

.PHONY : sources/ft_strmap.o

# target to build an object file
sources/ft_strmap.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strmap.c.o
.PHONY : sources/ft_strmap.c.o

sources/ft_strmap.i: sources/ft_strmap.c.i

.PHONY : sources/ft_strmap.i

# target to preprocess a source file
sources/ft_strmap.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strmap.c.i
.PHONY : sources/ft_strmap.c.i

sources/ft_strmap.s: sources/ft_strmap.c.s

.PHONY : sources/ft_strmap.s

# target to generate assembly for a file
sources/ft_strmap.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strmap.c.s
.PHONY : sources/ft_strmap.c.s

sources/ft_strmapi.o: sources/ft_strmapi.c.o

.PHONY : sources/ft_strmapi.o

# target to build an object file
sources/ft_strmapi.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strmapi.c.o
.PHONY : sources/ft_strmapi.c.o

sources/ft_strmapi.i: sources/ft_strmapi.c.i

.PHONY : sources/ft_strmapi.i

# target to preprocess a source file
sources/ft_strmapi.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strmapi.c.i
.PHONY : sources/ft_strmapi.c.i

sources/ft_strmapi.s: sources/ft_strmapi.c.s

.PHONY : sources/ft_strmapi.s

# target to generate assembly for a file
sources/ft_strmapi.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strmapi.c.s
.PHONY : sources/ft_strmapi.c.s

sources/ft_strncat.o: sources/ft_strncat.c.o

.PHONY : sources/ft_strncat.o

# target to build an object file
sources/ft_strncat.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strncat.c.o
.PHONY : sources/ft_strncat.c.o

sources/ft_strncat.i: sources/ft_strncat.c.i

.PHONY : sources/ft_strncat.i

# target to preprocess a source file
sources/ft_strncat.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strncat.c.i
.PHONY : sources/ft_strncat.c.i

sources/ft_strncat.s: sources/ft_strncat.c.s

.PHONY : sources/ft_strncat.s

# target to generate assembly for a file
sources/ft_strncat.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strncat.c.s
.PHONY : sources/ft_strncat.c.s

sources/ft_strncmp.o: sources/ft_strncmp.c.o

.PHONY : sources/ft_strncmp.o

# target to build an object file
sources/ft_strncmp.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strncmp.c.o
.PHONY : sources/ft_strncmp.c.o

sources/ft_strncmp.i: sources/ft_strncmp.c.i

.PHONY : sources/ft_strncmp.i

# target to preprocess a source file
sources/ft_strncmp.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strncmp.c.i
.PHONY : sources/ft_strncmp.c.i

sources/ft_strncmp.s: sources/ft_strncmp.c.s

.PHONY : sources/ft_strncmp.s

# target to generate assembly for a file
sources/ft_strncmp.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strncmp.c.s
.PHONY : sources/ft_strncmp.c.s

sources/ft_strncpy.o: sources/ft_strncpy.c.o

.PHONY : sources/ft_strncpy.o

# target to build an object file
sources/ft_strncpy.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strncpy.c.o
.PHONY : sources/ft_strncpy.c.o

sources/ft_strncpy.i: sources/ft_strncpy.c.i

.PHONY : sources/ft_strncpy.i

# target to preprocess a source file
sources/ft_strncpy.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strncpy.c.i
.PHONY : sources/ft_strncpy.c.i

sources/ft_strncpy.s: sources/ft_strncpy.c.s

.PHONY : sources/ft_strncpy.s

# target to generate assembly for a file
sources/ft_strncpy.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strncpy.c.s
.PHONY : sources/ft_strncpy.c.s

sources/ft_strnequ.o: sources/ft_strnequ.c.o

.PHONY : sources/ft_strnequ.o

# target to build an object file
sources/ft_strnequ.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strnequ.c.o
.PHONY : sources/ft_strnequ.c.o

sources/ft_strnequ.i: sources/ft_strnequ.c.i

.PHONY : sources/ft_strnequ.i

# target to preprocess a source file
sources/ft_strnequ.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strnequ.c.i
.PHONY : sources/ft_strnequ.c.i

sources/ft_strnequ.s: sources/ft_strnequ.c.s

.PHONY : sources/ft_strnequ.s

# target to generate assembly for a file
sources/ft_strnequ.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strnequ.c.s
.PHONY : sources/ft_strnequ.c.s

sources/ft_strnew.o: sources/ft_strnew.c.o

.PHONY : sources/ft_strnew.o

# target to build an object file
sources/ft_strnew.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strnew.c.o
.PHONY : sources/ft_strnew.c.o

sources/ft_strnew.i: sources/ft_strnew.c.i

.PHONY : sources/ft_strnew.i

# target to preprocess a source file
sources/ft_strnew.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strnew.c.i
.PHONY : sources/ft_strnew.c.i

sources/ft_strnew.s: sources/ft_strnew.c.s

.PHONY : sources/ft_strnew.s

# target to generate assembly for a file
sources/ft_strnew.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strnew.c.s
.PHONY : sources/ft_strnew.c.s

sources/ft_strnlen.o: sources/ft_strnlen.c.o

.PHONY : sources/ft_strnlen.o

# target to build an object file
sources/ft_strnlen.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strnlen.c.o
.PHONY : sources/ft_strnlen.c.o

sources/ft_strnlen.i: sources/ft_strnlen.c.i

.PHONY : sources/ft_strnlen.i

# target to preprocess a source file
sources/ft_strnlen.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strnlen.c.i
.PHONY : sources/ft_strnlen.c.i

sources/ft_strnlen.s: sources/ft_strnlen.c.s

.PHONY : sources/ft_strnlen.s

# target to generate assembly for a file
sources/ft_strnlen.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strnlen.c.s
.PHONY : sources/ft_strnlen.c.s

sources/ft_strnstr.o: sources/ft_strnstr.c.o

.PHONY : sources/ft_strnstr.o

# target to build an object file
sources/ft_strnstr.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strnstr.c.o
.PHONY : sources/ft_strnstr.c.o

sources/ft_strnstr.i: sources/ft_strnstr.c.i

.PHONY : sources/ft_strnstr.i

# target to preprocess a source file
sources/ft_strnstr.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strnstr.c.i
.PHONY : sources/ft_strnstr.c.i

sources/ft_strnstr.s: sources/ft_strnstr.c.s

.PHONY : sources/ft_strnstr.s

# target to generate assembly for a file
sources/ft_strnstr.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strnstr.c.s
.PHONY : sources/ft_strnstr.c.s

sources/ft_strrchr.o: sources/ft_strrchr.c.o

.PHONY : sources/ft_strrchr.o

# target to build an object file
sources/ft_strrchr.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strrchr.c.o
.PHONY : sources/ft_strrchr.c.o

sources/ft_strrchr.i: sources/ft_strrchr.c.i

.PHONY : sources/ft_strrchr.i

# target to preprocess a source file
sources/ft_strrchr.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strrchr.c.i
.PHONY : sources/ft_strrchr.c.i

sources/ft_strrchr.s: sources/ft_strrchr.c.s

.PHONY : sources/ft_strrchr.s

# target to generate assembly for a file
sources/ft_strrchr.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strrchr.c.s
.PHONY : sources/ft_strrchr.c.s

sources/ft_strsplit.o: sources/ft_strsplit.c.o

.PHONY : sources/ft_strsplit.o

# target to build an object file
sources/ft_strsplit.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strsplit.c.o
.PHONY : sources/ft_strsplit.c.o

sources/ft_strsplit.i: sources/ft_strsplit.c.i

.PHONY : sources/ft_strsplit.i

# target to preprocess a source file
sources/ft_strsplit.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strsplit.c.i
.PHONY : sources/ft_strsplit.c.i

sources/ft_strsplit.s: sources/ft_strsplit.c.s

.PHONY : sources/ft_strsplit.s

# target to generate assembly for a file
sources/ft_strsplit.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strsplit.c.s
.PHONY : sources/ft_strsplit.c.s

sources/ft_strstr.o: sources/ft_strstr.c.o

.PHONY : sources/ft_strstr.o

# target to build an object file
sources/ft_strstr.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strstr.c.o
.PHONY : sources/ft_strstr.c.o

sources/ft_strstr.i: sources/ft_strstr.c.i

.PHONY : sources/ft_strstr.i

# target to preprocess a source file
sources/ft_strstr.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strstr.c.i
.PHONY : sources/ft_strstr.c.i

sources/ft_strstr.s: sources/ft_strstr.c.s

.PHONY : sources/ft_strstr.s

# target to generate assembly for a file
sources/ft_strstr.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strstr.c.s
.PHONY : sources/ft_strstr.c.s

sources/ft_strsub.o: sources/ft_strsub.c.o

.PHONY : sources/ft_strsub.o

# target to build an object file
sources/ft_strsub.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strsub.c.o
.PHONY : sources/ft_strsub.c.o

sources/ft_strsub.i: sources/ft_strsub.c.i

.PHONY : sources/ft_strsub.i

# target to preprocess a source file
sources/ft_strsub.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strsub.c.i
.PHONY : sources/ft_strsub.c.i

sources/ft_strsub.s: sources/ft_strsub.c.s

.PHONY : sources/ft_strsub.s

# target to generate assembly for a file
sources/ft_strsub.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strsub.c.s
.PHONY : sources/ft_strsub.c.s

sources/ft_strtrim.o: sources/ft_strtrim.c.o

.PHONY : sources/ft_strtrim.o

# target to build an object file
sources/ft_strtrim.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strtrim.c.o
.PHONY : sources/ft_strtrim.c.o

sources/ft_strtrim.i: sources/ft_strtrim.c.i

.PHONY : sources/ft_strtrim.i

# target to preprocess a source file
sources/ft_strtrim.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strtrim.c.i
.PHONY : sources/ft_strtrim.c.i

sources/ft_strtrim.s: sources/ft_strtrim.c.s

.PHONY : sources/ft_strtrim.s

# target to generate assembly for a file
sources/ft_strtrim.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_strtrim.c.s
.PHONY : sources/ft_strtrim.c.s

sources/ft_swap.o: sources/ft_swap.c.o

.PHONY : sources/ft_swap.o

# target to build an object file
sources/ft_swap.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_swap.c.o
.PHONY : sources/ft_swap.c.o

sources/ft_swap.i: sources/ft_swap.c.i

.PHONY : sources/ft_swap.i

# target to preprocess a source file
sources/ft_swap.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_swap.c.i
.PHONY : sources/ft_swap.c.i

sources/ft_swap.s: sources/ft_swap.c.s

.PHONY : sources/ft_swap.s

# target to generate assembly for a file
sources/ft_swap.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_swap.c.s
.PHONY : sources/ft_swap.c.s

sources/ft_tolower.o: sources/ft_tolower.c.o

.PHONY : sources/ft_tolower.o

# target to build an object file
sources/ft_tolower.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_tolower.c.o
.PHONY : sources/ft_tolower.c.o

sources/ft_tolower.i: sources/ft_tolower.c.i

.PHONY : sources/ft_tolower.i

# target to preprocess a source file
sources/ft_tolower.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_tolower.c.i
.PHONY : sources/ft_tolower.c.i

sources/ft_tolower.s: sources/ft_tolower.c.s

.PHONY : sources/ft_tolower.s

# target to generate assembly for a file
sources/ft_tolower.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_tolower.c.s
.PHONY : sources/ft_tolower.c.s

sources/ft_toupper.o: sources/ft_toupper.c.o

.PHONY : sources/ft_toupper.o

# target to build an object file
sources/ft_toupper.c.o:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_toupper.c.o
.PHONY : sources/ft_toupper.c.o

sources/ft_toupper.i: sources/ft_toupper.c.i

.PHONY : sources/ft_toupper.i

# target to preprocess a source file
sources/ft_toupper.c.i:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_toupper.c.i
.PHONY : sources/ft_toupper.c.i

sources/ft_toupper.s: sources/ft_toupper.c.s

.PHONY : sources/ft_toupper.s

# target to generate assembly for a file
sources/ft_toupper.c.s:
	$(MAKE) -f CMakeFiles/get_next_line.dir/build.make CMakeFiles/get_next_line.dir/sources/ft_toupper.c.s
.PHONY : sources/ft_toupper.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... get_next_line"
	@echo "... get_next_line.o"
	@echo "... get_next_line.i"
	@echo "... get_next_line.s"
	@echo "... sources/ft_atoi.o"
	@echo "... sources/ft_atoi.i"
	@echo "... sources/ft_atoi.s"
	@echo "... sources/ft_bzero.o"
	@echo "... sources/ft_bzero.i"
	@echo "... sources/ft_bzero.s"
	@echo "... sources/ft_cpyuntil.o"
	@echo "... sources/ft_cpyuntil.i"
	@echo "... sources/ft_cpyuntil.s"
	@echo "... sources/ft_is_null_ptr.o"
	@echo "... sources/ft_is_null_ptr.i"
	@echo "... sources/ft_is_null_ptr.s"
	@echo "... sources/ft_isalnum.o"
	@echo "... sources/ft_isalnum.i"
	@echo "... sources/ft_isalnum.s"
	@echo "... sources/ft_isalpha.o"
	@echo "... sources/ft_isalpha.i"
	@echo "... sources/ft_isalpha.s"
	@echo "... sources/ft_isascii.o"
	@echo "... sources/ft_isascii.i"
	@echo "... sources/ft_isascii.s"
	@echo "... sources/ft_isblank.o"
	@echo "... sources/ft_isblank.i"
	@echo "... sources/ft_isblank.s"
	@echo "... sources/ft_isdigit.o"
	@echo "... sources/ft_isdigit.i"
	@echo "... sources/ft_isdigit.s"
	@echo "... sources/ft_isprint.o"
	@echo "... sources/ft_isprint.i"
	@echo "... sources/ft_isprint.s"
	@echo "... sources/ft_itoa.o"
	@echo "... sources/ft_itoa.i"
	@echo "... sources/ft_itoa.s"
	@echo "... sources/ft_lstadd.o"
	@echo "... sources/ft_lstadd.i"
	@echo "... sources/ft_lstadd.s"
	@echo "... sources/ft_lstaddback.o"
	@echo "... sources/ft_lstaddback.i"
	@echo "... sources/ft_lstaddback.s"
	@echo "... sources/ft_lstdel.o"
	@echo "... sources/ft_lstdel.i"
	@echo "... sources/ft_lstdel.s"
	@echo "... sources/ft_lstdelone.o"
	@echo "... sources/ft_lstdelone.i"
	@echo "... sources/ft_lstdelone.s"
	@echo "... sources/ft_lstiter.o"
	@echo "... sources/ft_lstiter.i"
	@echo "... sources/ft_lstiter.s"
	@echo "... sources/ft_lstmap.o"
	@echo "... sources/ft_lstmap.i"
	@echo "... sources/ft_lstmap.s"
	@echo "... sources/ft_lstnew.o"
	@echo "... sources/ft_lstnew.i"
	@echo "... sources/ft_lstnew.s"
	@echo "... sources/ft_memalloc.o"
	@echo "... sources/ft_memalloc.i"
	@echo "... sources/ft_memalloc.s"
	@echo "... sources/ft_memccpy.o"
	@echo "... sources/ft_memccpy.i"
	@echo "... sources/ft_memccpy.s"
	@echo "... sources/ft_memchr.o"
	@echo "... sources/ft_memchr.i"
	@echo "... sources/ft_memchr.s"
	@echo "... sources/ft_memcmp.o"
	@echo "... sources/ft_memcmp.i"
	@echo "... sources/ft_memcmp.s"
	@echo "... sources/ft_memcpy.o"
	@echo "... sources/ft_memcpy.i"
	@echo "... sources/ft_memcpy.s"
	@echo "... sources/ft_memdel.o"
	@echo "... sources/ft_memdel.i"
	@echo "... sources/ft_memdel.s"
	@echo "... sources/ft_memmove.o"
	@echo "... sources/ft_memmove.i"
	@echo "... sources/ft_memmove.s"
	@echo "... sources/ft_memset.o"
	@echo "... sources/ft_memset.i"
	@echo "... sources/ft_memset.s"
	@echo "... sources/ft_putchar.o"
	@echo "... sources/ft_putchar.i"
	@echo "... sources/ft_putchar.s"
	@echo "... sources/ft_putchar_fd.o"
	@echo "... sources/ft_putchar_fd.i"
	@echo "... sources/ft_putchar_fd.s"
	@echo "... sources/ft_putendl.o"
	@echo "... sources/ft_putendl.i"
	@echo "... sources/ft_putendl.s"
	@echo "... sources/ft_putendl_fd.o"
	@echo "... sources/ft_putendl_fd.i"
	@echo "... sources/ft_putendl_fd.s"
	@echo "... sources/ft_putnbr.o"
	@echo "... sources/ft_putnbr.i"
	@echo "... sources/ft_putnbr.s"
	@echo "... sources/ft_putnbr_fd.o"
	@echo "... sources/ft_putnbr_fd.i"
	@echo "... sources/ft_putnbr_fd.s"
	@echo "... sources/ft_putstr.o"
	@echo "... sources/ft_putstr.i"
	@echo "... sources/ft_putstr.s"
	@echo "... sources/ft_putstr_fd.o"
	@echo "... sources/ft_putstr_fd.i"
	@echo "... sources/ft_putstr_fd.s"
	@echo "... sources/ft_strcat.o"
	@echo "... sources/ft_strcat.i"
	@echo "... sources/ft_strcat.s"
	@echo "... sources/ft_strchr.o"
	@echo "... sources/ft_strchr.i"
	@echo "... sources/ft_strchr.s"
	@echo "... sources/ft_strclr.o"
	@echo "... sources/ft_strclr.i"
	@echo "... sources/ft_strclr.s"
	@echo "... sources/ft_strcmp.o"
	@echo "... sources/ft_strcmp.i"
	@echo "... sources/ft_strcmp.s"
	@echo "... sources/ft_strcpy.o"
	@echo "... sources/ft_strcpy.i"
	@echo "... sources/ft_strcpy.s"
	@echo "... sources/ft_strdel.o"
	@echo "... sources/ft_strdel.i"
	@echo "... sources/ft_strdel.s"
	@echo "... sources/ft_strdup.o"
	@echo "... sources/ft_strdup.i"
	@echo "... sources/ft_strdup.s"
	@echo "... sources/ft_strequ.o"
	@echo "... sources/ft_strequ.i"
	@echo "... sources/ft_strequ.s"
	@echo "... sources/ft_striter.o"
	@echo "... sources/ft_striter.i"
	@echo "... sources/ft_striter.s"
	@echo "... sources/ft_striteri.o"
	@echo "... sources/ft_striteri.i"
	@echo "... sources/ft_striteri.s"
	@echo "... sources/ft_strjoin.o"
	@echo "... sources/ft_strjoin.i"
	@echo "... sources/ft_strjoin.s"
	@echo "... sources/ft_strjoinch.o"
	@echo "... sources/ft_strjoinch.i"
	@echo "... sources/ft_strjoinch.s"
	@echo "... sources/ft_strjoinf.o"
	@echo "... sources/ft_strjoinf.i"
	@echo "... sources/ft_strjoinf.s"
	@echo "... sources/ft_strlcat.o"
	@echo "... sources/ft_strlcat.i"
	@echo "... sources/ft_strlcat.s"
	@echo "... sources/ft_strlen.o"
	@echo "... sources/ft_strlen.i"
	@echo "... sources/ft_strlen.s"
	@echo "... sources/ft_strmap.o"
	@echo "... sources/ft_strmap.i"
	@echo "... sources/ft_strmap.s"
	@echo "... sources/ft_strmapi.o"
	@echo "... sources/ft_strmapi.i"
	@echo "... sources/ft_strmapi.s"
	@echo "... sources/ft_strncat.o"
	@echo "... sources/ft_strncat.i"
	@echo "... sources/ft_strncat.s"
	@echo "... sources/ft_strncmp.o"
	@echo "... sources/ft_strncmp.i"
	@echo "... sources/ft_strncmp.s"
	@echo "... sources/ft_strncpy.o"
	@echo "... sources/ft_strncpy.i"
	@echo "... sources/ft_strncpy.s"
	@echo "... sources/ft_strnequ.o"
	@echo "... sources/ft_strnequ.i"
	@echo "... sources/ft_strnequ.s"
	@echo "... sources/ft_strnew.o"
	@echo "... sources/ft_strnew.i"
	@echo "... sources/ft_strnew.s"
	@echo "... sources/ft_strnlen.o"
	@echo "... sources/ft_strnlen.i"
	@echo "... sources/ft_strnlen.s"
	@echo "... sources/ft_strnstr.o"
	@echo "... sources/ft_strnstr.i"
	@echo "... sources/ft_strnstr.s"
	@echo "... sources/ft_strrchr.o"
	@echo "... sources/ft_strrchr.i"
	@echo "... sources/ft_strrchr.s"
	@echo "... sources/ft_strsplit.o"
	@echo "... sources/ft_strsplit.i"
	@echo "... sources/ft_strsplit.s"
	@echo "... sources/ft_strstr.o"
	@echo "... sources/ft_strstr.i"
	@echo "... sources/ft_strstr.s"
	@echo "... sources/ft_strsub.o"
	@echo "... sources/ft_strsub.i"
	@echo "... sources/ft_strsub.s"
	@echo "... sources/ft_strtrim.o"
	@echo "... sources/ft_strtrim.i"
	@echo "... sources/ft_strtrim.s"
	@echo "... sources/ft_swap.o"
	@echo "... sources/ft_swap.i"
	@echo "... sources/ft_swap.s"
	@echo "... sources/ft_tolower.o"
	@echo "... sources/ft_tolower.i"
	@echo "... sources/ft_tolower.s"
	@echo "... sources/ft_toupper.o"
	@echo "... sources/ft_toupper.i"
	@echo "... sources/ft_toupper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

